title: Gabe Montalvo Development Blog
description: programming and other things
show_downloads: false
google_analytics: UA-90773418-1
disqus: gabe-montalvo-blog
github:
  url: https://gamontalvo.github.io/blog.gmontalvo.me/
baseurl:
theme: jekyll-theme-minimal
paginate: 5
paginate_path: "page:num"
gems:
  - jemoji
github_link: https://github.com/gamontalvo
twitter_link: https://twitter.com/gmontalvoriv
reddit_link: https://www.reddit.com/user/theprimeprogram/
linkedin_link: https://www.linkedin.com/in/gabriel-montalvo-553931135
youtube_link: 
codepen_link: http://codepen.io/gmontalvoriv/